### PR TITLE
Intelligently handle document-local links

### PR DESCRIPTION
**Pull request by maxnikulin**
I have faced a site with links in the form of
``` html
<a href="/path/to/the/dir/#par">paragraph</a>
```
event if their targets are in the same document.
As a result the links in the captured page are not document-local
any more and lead to the original site.

I hope the following changes allow to work with the saved page.

Rewrite href attributes of "a" elements if their targets is within
the captured fragment but they are referenced by full path
or even by full URI.

Make local links work in the captured document even if hash
sign is in the middle of the href attribute.

In the case of page fragment capture, distinguish link targets
within the selection and outside of it.

Caveats:
* In the case of partial capture deep in the nested
page structure, the links to ancestors are considered local
however ancestors content is not included.
* Obsolete <A name="bla-bla-bla"> anchors are not handled

### CODE REVIEW

**Comment by danny0838** [comment]
Nice idea. But I cannot understand why adding a startNode argument for processDOMRecursively?

**Comment by maxnikulin** [comment]
Previously any link target in the document fragment
was unconditionally transformed into URI of the original page
and it was reasonable if a user captured just a paragraph
of a long document. My aim is to distinguish local and external links in
relation to selected region.

While processing a node, there are two options to determine
if the link target is local to the selection
or it leads outside of the captured fragment.
I considered iteration over node parents to get the root node.
It did not require to change signature of any functions
but I was afraid of performance degradation for documents
with abundant internal links.
Another way is just to pass the root node of the captured fragment
suitable for looking for children having specific ids.
Unfortunately it is useless to query aNode.ownerDocument.getElementById()
since cloned nodes belong to the original document.

I can submit a variant with iteration over parents for each link target.
Do you have a better idea?

**Comment by danny0838** [comment]
Well, my question was that you added a **startNode** argument to the progressDOMRecursively method, while you pass same value for both arguments of progressDOMRecursively. I wonder if it makes any difference with not adding the startNode argument.

**Comment by maxnikulin** [comment]
There is another call (this is a recursive method)
``` js
this.processDOMRecursively(curNode, rootNode);
```
I completely agree with you that invocation with the repeated argument
hardly can be referred to as an elegant solution.
On the other hand I am in doubt if optional second argument
(with fallback to the first one) is better.

**Comment by danny0838** [comment]
Thank you, I get it.

I wonder that the issue that the ancestor be considered included while its content are not fully captured is quite undesired. If we cannot solve it, i.e. preserves hash link only if the target element is fully captured—which could be difficult since ScrapBook X now supports capturing multiple selected fragments—I'd rather choose linking to the original page for every capture selection.

On the other hand, we could probably improve the issue that "links to the document itself with hash" be linked to the original page.

**Comment by danny0838** [comment]
Thank you, I get it.

We recently did several code reworks. Could you rebase this patch onto the latest master (1.12.23)?

**Comment by maxnikulin** [comment]
Please, have a look at the rebased patch

**Comment by danny0838** [comment]
Thank you. Here are still several issues:

1. We are more likelty to use sbCommonUtils.splitFileName (in modules/common.jsm) for anchor separation and comparison.
2. It doesn't seem necessary to add an isolated function `detectLocalHref()`, maybe we could move them to the if clause?
3. `querySelector` is not supported in older Firefox versions (<3.5), which could install ScrapBook X (>= 3.0). Would it work if we replace rootNode.querySelector('#some-id') with rootNode.getElementById(some-id)?

**Comment by maxnikulin** [comment]
> It doesn't seem necessary to add an isolated function detectLocalHref(), maybe we could move them to the if clause?

Sure. But it was much more convenient to make any of accept/reject decision at the any point
of the isolated function. I hope, I do not break logic while moving the function body.

> querySelector is not supported in older Firefox versions (<3.5), some of which could install ScrapBook X (>= 3.0). Would it work if we replace rootNode.querySelector('#some-id') with rootNode.getElementById(some-id)?

rootNode is an Element, not a Document, so getElementById does not help.
rootNode.ownerDocument is the original document, so it is useless
for testing if the link target is within the selected fragment
(moreover captured clone is outside of the original document's DOM tree).
Actually my code should not break ancient versions behavior besides
slowing down of processing. I add try-catch to handle selection syntax errors
due to odd anchors, but absent of querySelector method is treated in the same way.

> It is possible that http://some.url.com#anchor be linked to an element with name (rather than id) "anchor", which is not detected by your patch. What do you think about it?

Current behavior is preserved. HTML5 Standard recommends 'id' attribute,
'name' attribute is forbidden in XHTML 1.1. However archiving of really old pages
is the point.

Since Document.getElementsByName
is useless here, the issue with Selector API rises again.
Unfortunately querySelector("#nameda") ignore name attributes.
If you insist, I consider quoting of anchor for rootNode.querySelector("[name=nameda]").

I will submit the patch with in-line tests as a new pull request.

**Pull request closed without merging**
